/* ─────────────────────────────────────────────────────────
   Base project data
───────────────────────────────────────────────────────── */
const baseProjectData = [
    {id:1,title:"AI-PACU Study: Clinical Decision Support for Discharge & Escalation",faculty:"Brian Pitts, MD, MS",trainees:"Josephine Du",type:"Research",description:"Development and evaluation of an AI-based decision support tool to aid PACU nurses with escalation and discharge decisions using EHR-derived data.",skills:"Interest in perioperative medicine; basic data literacy; optional Python/R",time:"2–4 hrs/week",residentSlots:0,studentSlots:2,status:"Active",durationRange:"3–6 months (estimated)",targetDate:"TBD",lastUpdated:"2026-02-20",contactName:"Josephine Du (Project Lead)",contactEmail:""},
    {id:2,title:"Stroke Thrombectomy Anesthesia Protocol",faculty:"Brian Pitts, MD, MS; Christian Bohringer, MD",trainees:"Michael Agarado",type:"QI",description:"Quality improvement project to streamline anesthesia workflows for mechanical thrombectomy to reduce treatment delays.",skills:"Interest in neuroanesthesia and systems improvement",time:"2 hrs/week",residentSlots:1,studentSlots:0,status:"Active",durationRange:"8–12 weeks (estimated)",targetDate:"TBD",lastUpdated:"2026-02-10",contactName:"Michael Agarado (Trainee Lead)",contactEmail:""},
    {id:3,title:"BranchLab: Physiologic Airway Simulation",faculty:"Brian Pitts, MD, MS; Hannah Bechtold, MD",trainees:"Callum Rowe, MD; Derron Yu, MD; Ravina Brring, MD; Ellie Tsang",type:"Edu/Res",description:"Development of interactive, case-based simulations to teach physiologic airway management to anesthesia trainees.",skills:"Interest in education; optional UI/UX or web development",time:"Flexible",residentSlots:1,studentSlots:1,status:"Active",durationRange:"Flexible",targetDate:"TBD",lastUpdated:"2025-09-01",contactName:"Callum Rowe (Resident Lead)",contactEmail:""},
    {id:4,title:"Pediatric Anesthesia Safety Dashboard",faculty:"Faculty Lead TBD",trainees:"—",type:"QI",description:"Creation of a dashboard tracking perioperative safety metrics in pediatric anesthesia to support quality monitoring.",skills:"Basic data interpretation; interest in patient safety",time:"2–4 hrs/week",residentSlots:0,studentSlots:2,status:"Planning",durationRange:"TBD",targetDate:"TBD",lastUpdated:"2025-10-15",contactName:"Faculty Lead TBD",contactEmail:""},
    {id:5,title:"EVD Safety Campaign",faculty:"Faculty Lead TBD",trainees:"—",type:"QI",description:"Quality improvement initiative focused on improving safety practices surrounding external ventricular drain management.",skills:"Interest in neurosurgical or neurocritical care safety",time:"1–2 hrs/week",residentSlots:0,studentSlots:0,status:"Planning",durationRange:"TBD",targetDate:"TBD",lastUpdated:"2025-07-01",contactName:"Faculty Lead TBD",contactEmail:""},
    {id:6,title:"Patient self-reported duration of analgesia after shoulder surgery and interscalene block with and without perineural adjuncts",faculty:"Robin Aldwinckle, B.M.B.S., F.R.C.A.",trainees:"—",type:"Research",description:"Observational study assessing patient-reported analgesia duration following interscalene blocks with adjunct medications.",skills:"Interest in regional anesthesia; chart review skills",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Active",durationRange:"TBD",targetDate:"TBD",lastUpdated:"2025-12-01",contactName:"Robin Aldwinckle",contactEmail:""},
    {id:7,title:"A comparison of 0.25% bupivacaine vs bupivacaine + clonidine/dexamethasone vs buprenorphine vs liposomal bupivacaine for outpatient arthroscopic shoulder surgery",faculty:"Robin Aldwinckle, B.M.B.S., F.R.C.A.",trainees:"—",type:"Research",description:"Comparative effectiveness study of local anesthetic strategies for postoperative pain control in shoulder surgery.",skills:"Interest in regional anesthesia; data abstraction",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Active",durationRange:"TBD",targetDate:"TBD",lastUpdated:"2025-12-01",contactName:"Robin Aldwinckle",contactEmail:""},
    {id:8,title:"Evaluation of dynamic monitors for the prediction of volume responsiveness in patients with and without diastolic dysfunction",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Physiologic study evaluating the accuracy of dynamic hemodynamic monitors in predicting fluid responsiveness.",skills:"Interest in cardiac physiology; basic statistics",time:"2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed",durationRange:"Completed",targetDate:"Completed",lastUpdated:"2024-06-01",contactName:"Neal Fleming",contactEmail:""},
    {id:9,title:"Do preoperative PECS I and II nerve blocks reduce post-mastectomy opioid consumption, LOS, and improve comfort?",faculty:"Jon Zhou, MD",trainees:"—",type:"Research",description:"Retrospective cohort study evaluating the impact of PECS blocks on postoperative outcomes after mastectomy.",skills:"Interest in regional anesthesia; chart review",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Completed",durationRange:"Completed",targetDate:"Completed",lastUpdated:"2024-06-01",contactName:"Jon Zhou",contactEmail:""},
    {id:10,title:"Transversus abdominus plane (TAP) blocks with ropivacaine continuous infusion catheters vs liposomal bupivacaine after renal transplant",faculty:"Dr. Furukawa",trainees:"—",type:"Clin Trial",description:"Prospective randomized control trial comparing two different TAP block methods (ropivacaine continuous infusion catheters vs single-dose liposomal bupivacaine) for controlling pain after kidney transplant surgery, evaluating effectiveness and costs.",skills:"Evaluate and analyze clinical data",time:"2–3 hrs/week",residentSlots:1,studentSlots:1,status:"Active",durationRange:"TBD",targetDate:"TBD",lastUpdated:"2026-03-01",contactName:"Dr. Furukawa",contactEmail:""}
];

const tailRows = [
    {id:11,title:"Concurrent use of ultrasound-tagged near-infrared spectroscopy and near-infrared spectroscopy",faculty:"Bradlee Bachar",trainees:"—",type:"Research",description:"Feasibility and validation study combining ultrasound-tagged NIRS with standard NIRS monitoring.",skills:"Interest in monitoring technology",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:12,title:"Post-operative opioid usage, adverse events, and LOS after TAP blocks in renal transplant patients",faculty:"Kristin Bennett, D.O.",trainees:"—",type:"Research",description:"Retrospective outcomes study examining opioid use and complications after TAP block utilization.",skills:"Chart review skills; interest in pain outcomes",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Completed"},
    {id:13,title:"Effect of dexmedetomidine on postoperative recovery during low-income country cleft surgery missions",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Observational study evaluating perioperative dexmedetomidine use during international surgical missions.",skills:"Interest in global health anesthesia",time:"1–2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:14,title:"Sugammadex: Impact on Practice and Outcomes",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Assessment of clinical practice changes and outcomes following the introduction of sugammadex.",skills:"Interest in outcomes research",time:"1–2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:15,title:"Effects of IV fluid bolus on assessment of left ventricular diastolic function",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Physiologic echocardiography-based study examining how fluid boluses alter diastolic measurements.",skills:"Interest in cardiac ultrasound",time:"2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:16,title:"Comparing Continuous Cardiac Output Monitors in Cardiothoracic Surgery",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Comparative evaluation of continuous cardiac output monitoring devices during cardiac surgery.",skills:"Interest in cardiothoracic anesthesia",time:"2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:17,title:"Comparing Dynamic Parameters of Continuous Cardiac Function Monitors in Cardiothoracic Surgery",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Study comparing dynamic cardiac performance parameters across monitoring platforms.",skills:"Interest in hemodynamics",time:"2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:18,title:"Impact of the introduction of Sugammadex on 30-day postoperative readmission rates",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Retrospective outcomes study examining readmission rates after sugammadex adoption.",skills:"Basic statistics; chart review",time:"1–2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:19,title:"Impact of the introduction of Sugammadex on provider practice and PACU ventilation",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Practice-pattern analysis of neuromuscular reversal strategies and PACU ventilation.",skills:"Interest in perioperative workflow",time:"1–2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:20,title:"Infant memory, visual attention, and cognitive testing pre- and post-anesthesia",faculty:"Cathy Lammers, MD",trainees:"—",type:"Research",description:"Prospective neurodevelopmental assessment study in infants undergoing anesthesia.",skills:"Interest in pediatric anesthesia research",time:"2 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:21,title:"The perioperative use of hemodynamic monitor devices and surgical outcomes",faculty:"Hong Liu, MD",trainees:"—",type:"Research",description:"Large-scale observational study linking hemodynamic monitoring strategies to surgical outcomes.",skills:"Data analysis interest",time:"2–3 hrs/week",residentSlots:1,studentSlots:0,status:"Active"},
    {id:22,title:"Dexmedetomidine and renal transplants",faculty:"Hong Liu, MD",trainees:"—",type:"Research",description:"Evaluation of dexmedetomidine use and outcomes in renal transplant recipients.",skills:"Interest in transplant anesthesia",time:"1–2 hrs/week",residentSlots:1,studentSlots:0,status:"Active"},
    {id:23,title:"Impact of race in perioperative pain management in pediatric tonsillectomy and adenoidectomy",faculty:"Niroop Ravula, M.B.B.S., F.R.C.A.",trainees:"—",type:"Research",description:"Health equity study examining racial disparities in perioperative pain management.",skills:"Interest in disparities research",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:24,title:"Minimally invasive hemodynamic monitors during acute normovolemic hemodilution",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Physiologic study of minimally invasive monitors during controlled hemodilution.",skills:"Interest in hemodynamic physiology",time:"2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:25,title:"Does Video-Assisted Self Review Help Students Learn a New Skill Faster?",faculty:"Neal Fleming, MD, PhD; Brian Pitts, MD, MEd",trainees:"—",type:"Edu/Res",description:"Educational research study evaluating video-assisted self-review for procedural skill acquisition.",skills:"Interest in medical education",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Completed"},
    {id:26,title:"Non-diagnostic serum troponin as a marker for perioperative risk",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Outcomes study assessing prognostic value of low-level perioperative troponin elevations.",skills:"Basic statistics",time:"1–2 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:27,title:"Modified pre-operative oral acetaminophen vs intravenous acetaminophen",faculty:"Cathy Lammers, MD",trainees:"—",type:"Research",description:"Comparative study of oral versus IV acetaminophen for perioperative analgesia.",skills:"Interest in pain management",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:28,title:"Etomidate + propofol vs etomidate vs propofol for induction: pilot observational study",faculty:"Hong Liu, MD",trainees:"—",type:"Research",description:"Pilot observational study comparing induction agent strategies.",skills:"Interest in anesthetic pharmacology",time:"1–2 hrs/week",residentSlots:1,studentSlots:0,status:"Active"},
    {id:29,title:"TAP block catheters vs liposomal bupivacaine after colorectal surgery",faculty:"Jon Zhou, MD",trainees:"—",type:"Clin Trial",description:"Prospective randomized trial evaluating analgesic strategies after colorectal surgery.",skills:"Interest in clinical trials",time:"2–3 hrs/week",residentSlots:1,studentSlots:0,status:"Completed"},
    {id:30,title:"Merck: Impact of Quantitative Neuromuscular Monitoring and Sugammadex Reversal Following Abdominal Surgery",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Clin Trial",description:"Before/after study evaluating the impact of monitoring and reversal guidelines for neuromuscular blocking drugs on post-operative outcomes for patients undergoing abdominal surgeries, including continuous blood oxygen saturation monitoring via wearable device for 24 hours post-operatively.",skills:"Assist with device placement and retrieval; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:2,status:"Active"},
    {id:31,title:"Edwards Autoregulation: Observational Data Collection for Autoregulation Algorithm Development",faculty:"Hong Liu, MD",trainees:"—",type:"Research",description:"Observational study using non-invasive sensors and an arterial catheter to compare the accuracy of non-invasive sensors to measure blood pressure throughout surgical procedures vs standard of care monitors.",skills:"Evaluate and analyze clinical data",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:32,title:"Edwards ClearSight: ClearSight NextGen System Clinical Development Study",faculty:"Hong Liu, MD",trainees:"—",type:"Clin Trial",description:"Study involving blood pressure devices placed on patient fingers and arterial catheter, collecting heart function and blood pressure data via HemoSphere Monitor for approximately 4 hours to develop a new non-invasive finger-cuff blood pressure device.",skills:"Assist with device placement and retrieval; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:33,title:"Edwards Smart Trends: Acumen HPI Smart Alerts and Smart Trends for Intra-operative Hemodynamic Management",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Clin Trial",description:"Study evaluating whether automated prompts from Acumen HPI Smart Alerts and Smart Trends improve compliance with a pre-defined hemodynamic management plan to reduce low blood pressure and kidney injury during major elective non-cardiac surgery.",skills:"Assist with device placement and retrieval; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:34,title:"Racial Bias: Prospective Racial Bias Data Collection Study",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Study evaluating potential hemoglobin saturation (SpO2) measurement bias in finger pulse oximetry devices across different skin tones, using arterial blood gas data and the Massey Martin Skin Tone scale to assess measurement discrepancies.",skills:"Assist in data collection; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:2,status:"Active"},
    {id:35,title:"Rostrum OR: Evaluation of Non-Invasive Pulmonary Health Parameters for Acute Care Medicine",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Study of the VQm Pulmonary Health Monitor (PHM) measuring lung air volume distribution, functional residual capacity, dead space, pulmonary blood flow, and shunt fraction during surgical procedures, compared against GE Carescape ventilator measurements.",skills:"Assist in data collection; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:36,title:"Rostrum ICU: Evaluation of VQm Pulmonary Health Monitor for Intensive Care Medicine",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Evaluation of the VQm Pulmonary Health Monitor in an ICU setting to ensure comparable measurements to current monitors for assessing the impact of mechanical ventilation on lung and heart function, with monitoring up to 72 hours.",skills:"Assist in data collection; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:37,title:"Vertex Study: VX24-548-108 Phase 3b Non-Opioid Pain Management",faculty:"Dr. Copenhaver",trainees:"—",type:"Clin Trial",description:"Phase 3b study investigating use of an unapproved non-opioid highly selective voltage-gated sodium channel inhibitor as part of multimodal postoperative pain management.",skills:"Assist in data collection; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:38,title:"APPL0010: Feasibility of Wireless ECG and Vital Signs Monitor",faculty:"Neal Fleming, MD, PhD",trainees:"—",type:"Research",description:"Feasibility study evaluating experimental wireless vital signs monitoring systems (INVSENSOR0057 and Radius VSM ECG) in the Electrophysiology Lab and ICU, comparing accuracy and reliability against standard wired monitoring systems.",skills:"Assist in data collection; evaluate and analyze clinical data",time:"2–4 hrs/week",residentSlots:0,studentSlots:1,status:"Active"},
    {id:39,title:"VR Study: Audiovisual Distraction with Virtual Reality in Prone Interventional Pain Procedures",faculty:"Dr. Jung",trainees:"—",type:"Research",description:"Study investigating whether Virtual Reality (VR) audiovisual distraction can reduce anxiety, decrease pain levels, and improve patient satisfaction during prone interventional pain procedures, with pre-, intra-, and post-procedure surveys.",skills:"Evaluate and analyze clinical data",time:"1–2 hrs/week",residentSlots:0,studentSlots:1,status:"Active"}
].map(p => ({
    ...p,
    durationRange: p.status === "Completed" ? "Completed" : "TBD",
    targetDate: p.status === "Completed" ? "Completed" : "TBD",
    lastUpdated: p.status === "Completed" ? "2024-06-01" : "2025-12-01",
    contactName: (p.faculty || "Not listed").split(";")[0].trim() || "Not listed",
    contactEmail: ""
}));
