/* ─────────────────────────────────────────────────────────
   Project data — Demo / sample listings
   baseProjectData: primary projects
   tailRows: additional projects appended after base
───────────────────────────────────────────────────────── */

const baseProjectData = [
    {
        id: 1,
        title: "Point-of-Care Ultrasound for Regional Anesthesia: A Retrospective Outcomes Analysis",
        faculty: "Dr. Sarah Chen",
        trainees: "R. Patel (CA-2)",
        type: "Research",
        description: "Retrospective chart review examining block success rates and complication profiles when POCUS-guided regional techniques are performed by trainees versus attendings. Primary outcome is block failure rate at 30 minutes.",
        skills: "Chart review, REDCap, basic statistics",
        time: "3–5 hrs/week",
        status: "Active",
        durationRange: "12–16 weeks",
        targetDate: "ASA Oct 2026",
        lastUpdated: "2026-03-10",
        studentSlots: 1,
        residentSlots: 1,
        contactName: "Dr. Sarah Chen",
        contactEmail: "schen@example.edu"
    },
    {
        id: 2,
        title: "Opioid-Free Anesthesia Pathway for Ambulatory Knee Arthroscopy",
        faculty: "Dr. James Ortiz",
        trainees: "—",
        type: "QI",
        description: "Quality improvement initiative to implement and evaluate an opioid-free anesthetic protocol for outpatient knee arthroscopy. Tracks PACU pain scores, rescue opioid use, and patient satisfaction at 24 hours.",
        skills: "QI methodology, data collection, PDSA cycles",
        time: "2–4 hrs/week",
        status: "Active",
        durationRange: "8–12 weeks",
        targetDate: "PGA Dec 2026",
        lastUpdated: "2026-03-15",
        studentSlots: 2,
        residentSlots: 1,
        contactName: "Dr. James Ortiz",
        contactEmail: "jortiz@example.edu"
    },
    {
        id: 3,
        title: "Machine Learning Prediction of Post-Operative Nausea and Vomiting",
        faculty: "Dr. Anita Gupta",
        trainees: "M. Thompson (MS-4), K. Liu (CA-1)",
        type: "Research",
        description: "Developing and validating a gradient-boosted decision tree model to predict PONV risk using preoperative and intraoperative variables from the EMR. Aims to outperform the Apfel score.",
        skills: "Python, scikit-learn, clinical data extraction",
        time: "5–8 hrs/week",
        status: "Active",
        durationRange: "6–9 months",
        targetDate: "IARS Mar 2027",
        lastUpdated: "2026-02-28",
        studentSlots: 0,
        residentSlots: 1,
        contactName: "Dr. Anita Gupta",
        contactEmail: "agupta@example.edu"
    },
    {
        id: 4,
        title: "Simulation-Based Curriculum for Difficult Airway Management",
        faculty: "Dr. Michael Torres",
        trainees: "J. Adams (CA-3)",
        type: "Edu/Res",
        description: "Designing and evaluating a longitudinal simulation curriculum for advanced airway techniques. Pre/post assessments use validated checklists and global rating scales on high-fidelity mannequins.",
        skills: "Survey design, simulation, educational research methods",
        time: "2–3 hrs/week",
        status: "Active",
        durationRange: "16–20 weeks",
        targetDate: "AUA Spring 2027",
        lastUpdated: "2026-03-01",
        studentSlots: 1,
        residentSlots: 0,
        contactName: "Dr. Michael Torres",
        contactEmail: "mtorres@example.edu"
    },
    {
        id: 5,
        title: "Dexmedetomidine vs Propofol Sedation for Awake Craniotomy: A Prospective RCT",
        faculty: "Dr. Lisa Nakamura",
        trainees: "A. Fernandez (CA-2), P. Singh (CA-3)",
        type: "Clin Trial",
        description: "Single-center prospective randomized trial comparing patient satisfaction and intraoperative hemodynamic stability between dexmedetomidine and propofol-based sedation protocols for awake craniotomy.",
        skills: "IRB protocols, patient enrollment, data entry",
        time: "4–6 hrs/week",
        status: "Active",
        durationRange: "12 months",
        targetDate: "Anesthesiology Journal 2027",
        lastUpdated: "2026-03-18",
        studentSlots: 1,
        residentSlots: 1,
        contactName: "Dr. Lisa Nakamura",
        contactEmail: "lnakamura@example.edu"
    },
    {
        id: 6,
        title: "Reducing Perioperative Hypothermia in Geriatric Hip Fracture Patients",
        faculty: "Dr. Robert Kim",
        trainees: "S. Martinez (CA-1)",
        type: "QI",
        description: "Multidisciplinary QI project implementing a forced-air warming bundle for geriatric hip fracture patients. Measures core temperature on OR arrival, at incision, and in PACU, with secondary outcomes of SSI rates and length of stay.",
        skills: "Data abstraction, run charts, stakeholder engagement",
        time: "2–3 hrs/week",
        status: "Active",
        durationRange: "10–14 weeks",
        targetDate: "APSF Newsletter 2026",
        lastUpdated: "2026-01-20",
        studentSlots: 1,
        residentSlots: 1,
        contactName: "Dr. Robert Kim",
        contactEmail: "rkim@example.edu"
    },
    {
        id: 7,
        title: "Spinal Anesthesia Dosing in Morbid Obesity: A Dose-Finding Study",
        faculty: "Dr. Emily Watson",
        trainees: "—",
        type: "Research",
        description: "Prospective observational study correlating intrathecal bupivacaine dose with sensory block height in patients with BMI > 40. Uses ultrasound-measured spinal canal depth as a novel dosing predictor.",
        skills: "Patient recruitment, ultrasound measurements, statistical analysis",
        time: "3–4 hrs/week",
        status: "Planning",
        durationRange: "6–8 months",
        targetDate: "SOAP 2027",
        lastUpdated: "2026-03-05",
        studentSlots: 1,
        residentSlots: 2,
        contactName: "Dr. Emily Watson",
        contactEmail: "ewatson@example.edu"
    },
    {
        id: 8,
        title: "Burnout and Resilience Among Anesthesiology Residents: A Multi-Site Survey",
        faculty: "Dr. David Park",
        trainees: "C. Nguyen (CA-2)",
        type: "Edu/Res",
        description: "Cross-sectional survey study using the Maslach Burnout Inventory and Connor-Davidson Resilience Scale across three academic anesthesiology programs. Explores associations between schedule structure, autonomy, and well-being.",
        skills: "Survey distribution, Qualtrics, multivariate regression",
        time: "2–4 hrs/week",
        status: "Completed",
        durationRange: "Completed",
        targetDate: "Published A&A 2026",
        lastUpdated: "2025-12-15",
        studentSlots: 0,
        residentSlots: 0,
        contactName: "Dr. David Park",
        contactEmail: "dpark@example.edu"
    }
];

const tailRows = [
    {
        id: 9,
        title: "Enhanced Recovery After Cardiac Surgery (ERACS) Protocol Implementation",
        faculty: "Dr. Karen Zhao",
        trainees: "T. Brown (CA-3)",
        type: "QI",
        description: "Implementing a standardized ERACS pathway including preoperative carbohydrate loading, goal-directed fluid therapy, and multimodal analgesia. Primary endpoint is ICU length of stay.",
        skills: "Protocol development, multidisciplinary coordination, SPC charts",
        time: "3–5 hrs/week",
        status: "Active",
        durationRange: "16–24 weeks",
        targetDate: "SCA Annual Meeting 2027",
        lastUpdated: "2026-03-12",
        studentSlots: 1,
        residentSlots: 0,
        contactName: "Dr. Karen Zhao",
        contactEmail: "kzhao@example.edu"
    },
    {
        id: 10,
        title: "EEG-Guided Anesthetic Depth Monitoring in Pediatric Patients",
        faculty: "Dr. William Harris",
        trainees: "—",
        type: "Research",
        description: "Prospective study evaluating processed EEG indices for titrating sevoflurane in children aged 2–8 undergoing tonsillectomy. Compares emergence agitation and recovery times between EEG-guided and standard protocols.",
        skills: "Pediatric OR exposure, EEG data processing, clinical documentation",
        time: "4–6 hrs/week",
        status: "Planning",
        durationRange: "8–12 months",
        targetDate: "SPA Fall 2027",
        lastUpdated: "2026-02-10",
        studentSlots: 1,
        residentSlots: 1,
        contactName: "Dr. William Harris",
        contactEmail: "wharris@example.edu"
    },
    {
        id: 11,
        title: "Impact of Preoperative Anxiety Screening on Same-Day Surgery Cancellations",
        faculty: "Dr. Rachel Green",
        trainees: "L. Davis (MS-3)",
        type: "Research",
        description: "Evaluating whether routine GAD-7 screening at the preoperative clinic reduces day-of-surgery cancellations in anxious patients. Intervention arm receives targeted anxiolytic counseling and pharmacologic bridging.",
        skills: "Patient screening, REDCap, literature review",
        time: "2–3 hrs/week",
        status: "Active",
        durationRange: "10–14 weeks",
        targetDate: "ASA Oct 2026",
        lastUpdated: "2025-10-05",
        studentSlots: 1,
        residentSlots: 0,
        contactName: "Dr. Rachel Green",
        contactEmail: "rgreen@example.edu"
    },
    {
        id: 12,
        title: "Ketamine Infusion Protocols for Chronic Pain: Systematic Review and Meta-Analysis",
        faculty: "Dr. Anita Gupta",
        trainees: "N. Shah (CA-1), B. Lee (MS-4)",
        type: "Research",
        description: "Systematic review and meta-analysis of subanesthetic ketamine infusion protocols for chronic non-cancer pain. Examines dose-response relationships, duration of effect, and adverse event profiles across published RCTs.",
        skills: "Literature search (PubMed, Embase), PRISMA, RevMan/Stata",
        time: "5–8 hrs/week",
        status: "Active",
        durationRange: "12–16 weeks",
        targetDate: "Regional Anesthesia & Pain Medicine 2026",
        lastUpdated: "2026-03-20",
        studentSlots: 0,
        residentSlots: 1,
        contactName: "Dr. Anita Gupta",
        contactEmail: "agupta@example.edu"
    }
];
